import { describe, it, expect } from "vitest";
import { renderWorkflow, thresholdEnv, parseThresholdEnv, envName } from "../lib/ci";
import { DEFAULT_THRESHOLDS } from "../lib/gates";

describe("thresholdEnv", () => {
  it("exports every threshold key", () => {
    const names = thresholdEnv().map(([k]) => k);
    for (const k of Object.keys(DEFAULT_THRESHOLDS)) expect(names).toContain(envName(k));
  });

  it("renders arrays comma-joined so the Actions UI stays readable", () => {
    const v = Object.fromEntries(thresholdEnv());
    expect(v[envName("security_severity_block")]).toBe("high,critical");
  });

  it("is deterministically ordered", () => {
    expect(thresholdEnv()).toEqual(thresholdEnv());
  });
});

describe("renderWorkflow — drift protection", () => {
  // THE test this module exists for: every number in CI must come from DEFAULT_THRESHOLDS.
  // If someone hard-codes one into the template, these values stop matching and this fails.
  it("emits exactly the source thresholds, with no hand-written copies", () => {
    const parsed = parseThresholdEnv(renderWorkflow());
    for (const [k, v] of Object.entries(DEFAULT_THRESHOLDS)) {
      expect(parsed[envName(k)]).toBe(Array.isArray(v) ? v.join(",") : String(v));
    }
    expect(Object.keys(parsed)).toHaveLength(Object.keys(DEFAULT_THRESHOLDS).length);
  });

  it("follows a custom threshold set rather than the default", () => {
    const custom = { ...DEFAULT_THRESHOLDS, coverage_min_pct: 95, error_rate_pct: 0.05 };
    const parsed = parseThresholdEnv(renderWorkflow({ thresholds: custom }));
    expect(parsed[envName("coverage_min_pct")]).toBe("95");
    expect(parsed[envName("error_rate_pct")]).toBe("0.05");
  });

  it("references the coverage gate through its env var, never a literal", () => {
    const y = renderWorkflow();
    expect(y).toContain(`env.${envName("coverage_min_pct")}`);
    // the literal 90 must not appear as a bare threshold in the coverage step
    const covStep = y.slice(y.indexOf("Coverage gate"), y.indexOf("Security gate"));
    expect(covStep).not.toMatch(/pct\s*<\s*90/);
  });
});

describe("renderWorkflow — structure", () => {
  const y = renderWorkflow();

  it("is marked generated so nobody hand-edits it", () => {
    expect(y.startsWith("# GENERATED by pipeline/lib/ci.ts")).toBe(true);
  });

  it("declares name, triggers and a job", () => {
    expect(y).toContain("name: eCym Pipeline");
    expect(y).toMatch(/on:\n\s+push:\n\s+branches: \[main\]/);
    expect(y).toContain("jobs:");
    expect(y).toContain("  pipeline:");
  });

  it("honours branch and node overrides", () => {
    const c = renderWorkflow({ branch: "develop", node: "22" });
    expect(c).toContain("branches: [develop]");
    expect(c).toContain('node-version: "22"');
  });

  it("captures run_id and git sha for reproducibility", () => {
    expect(y).toContain("run_id=$(uuidgen)");
    expect(y).toContain("git_sha=");
  });

  it("orders the gates cheapest-first: typecheck → unit → coverage → security → run", () => {
    const at = (s: string) => y.indexOf(s);
    expect(at("Typecheck")).toBeLessThan(at("Unit tests"));
    expect(at("Unit tests")).toBeLessThan(at("Coverage gate"));
    expect(at("Coverage gate")).toBeLessThan(at("Security gate"));
    expect(at("Security gate")).toBeLessThan(at("Pipeline run"));
  });

  // security_scan must sit before anything that could merge — the prompt is explicit.
  it("runs the security gate before the pipeline run and uploads artefacts even on failure", () => {
    expect(y.indexOf("Security gate")).toBeLessThan(y.indexOf("Pipeline run"));
    expect(y).toContain("if: always()");
  });

  it("fails when coverage measured nothing, instead of treating it as 0-but-fine", () => {
    expect(y).toContain("coverage was not measured");
  });

  it("indents every env entry consistently (valid YAML block)", () => {
    const envBlock = y.slice(y.indexOf("env:\n") + 5, y.indexOf("jobs:"));
    const lines = envBlock.split("\n").filter((l) => l.trim());
    expect(lines.every((l) => /^ {2}GATE_[A-Z0-9_]+: ".*"$/.test(l))).toBe(true);
  });
});

describe("parseThresholdEnv", () => {
  it("returns nothing for a yaml with no gates", () => {
    expect(parseThresholdEnv("name: x\non: push\n")).toEqual({});
    expect(parseThresholdEnv("")).toEqual({});
    expect(parseThresholdEnv(undefined as never)).toEqual({});
  });

  it("ignores deeper-indented lookalikes", () => {
    expect(parseThresholdEnv('    GATE_FAKE: "1"\n')).toEqual({});
  });
});
