// CI workflow rendering (pure) — one source of truth for every threshold.
//
// WHY THIS EXISTS
// The prompt requires a GitHub-Actions YAML that "fails early on any quality-gate violation".
// The obvious way to write it is to type the numbers into the YAML. That is exactly how a
// CI gate and a local gate drift apart: someone tightens `coverage_min_pct` in
// `lib/gates.ts`, CI keeps waving through 70 %, and the pipeline reports green in two places
// that no longer mean the same thing.
//
// So the YAML is RENDERED from `DEFAULT_THRESHOLDS`. There is no second copy to update, and
// `tests/ci.test.ts` asserts every threshold in the output came from the source object —
// a drift is a test failure, not a discovery six weeks later.
//
// Hand-rolled emitter rather than a YAML library: the output is a fixed, known shape, and
// this repo's zero-dependency posture means not adding a serialiser to print 60 lines.
import { DEFAULT_THRESHOLDS, type Thresholds } from "./gates";

export interface CiOptions {
  thresholds?: Thresholds;
  /** Node version the workflow installs. */
  node?: string;
  /** Branch the workflow watches. */
  branch?: string;
  /** Coverage scope whose floor the pipeline lane enforces. */
  coverageScope?: string;
}

/** Env var name for a threshold key — the single place the mapping is defined. */
export const envName = (key: string): string => `GATE_${key.toUpperCase()}`;

/**
 * Threshold → env pairs, in a stable order.
 *
 * Arrays are joined with commas rather than JSON-encoded so the value stays readable in the
 * Actions UI, where an operator reads it to understand why a run failed.
 */
export function thresholdEnv(t: Thresholds = DEFAULT_THRESHOLDS): Array<[string, string]> {
  return Object.entries(t)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => [envName(k), Array.isArray(v) ? v.join(",") : String(v)] as [string, string]);
}

export function renderWorkflow(o: CiOptions = {}): string {
  const t = o.thresholds ?? DEFAULT_THRESHOLDS;
  const node = o.node ?? "24";
  const branch = o.branch ?? "main";
  const scope = o.coverageScope ?? "pipeline/lib";
  const env = thresholdEnv(t).map(([k, v]) => `  ${k}: "${v}"`).join("\n");

  return `# GENERATED by pipeline/lib/ci.ts — do not edit by hand.
# Every threshold below is rendered from lib/gates.ts:DEFAULT_THRESHOLDS, so the CI gate and
# the local gate cannot disagree. Change the numbers there and re-run:
#   npx tsx pipeline/bin/run.ts --emit-ci
name: eCym Pipeline

on:
  push:
    branches: [${branch}]
  pull_request:
    branches: [${branch}]

env:
${env}

jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "${node}"
          cache: npm

      - name: Install
        run: npm ci

      # Benchmark start: the run id and git sha make the results reproducible, which is the
      # whole point of recording environment metadata.
      - name: Benchmark metadata
        id: meta
        run: |
          echo "run_id=$(uuidgen)" >> "$GITHUB_OUTPUT"
          echo "git_sha=\${{ github.sha }}" >> "$GITHUB_OUTPUT"

      - name: Typecheck
        run: npx tsc --noEmit

      # Pure-core lane first: it is fast and it fails for reasons that are always real bugs,
      # so a broken core never burns the slower jobs below.
      - name: Unit tests (pure core)
        run: npx vitest run --project pipeline

      - name: Coverage gate (${scope} ≥ \${{ env.${envName("coverage_min_pct")} }}%)
        run: |
          npx vitest run --project pipeline --coverage.enabled \\
            --coverage.reporter=json-summary \\
            --coverage.reportsDirectory=coverage-pipeline \\
            --coverage.thresholds.lines=0 --coverage.thresholds.functions=0 \\
            --coverage.thresholds.branches=0
          node -e '
            const d = require("./coverage-pipeline/coverage-summary.json");
            const v = Object.entries(d).filter(([k]) => k.includes("${scope}")).map(([, x]) => x.lines.pct);
            const pct = v.length ? v.reduce((a, b) => a + b, 0) / v.length : 0;
            const min = Number(process.env.${envName("coverage_min_pct")});
            console.log("coverage", pct.toFixed(2), "min", min);
            if (!v.length) { console.error("no files under ${scope} — coverage was not measured"); process.exit(1); }
            if (pct < min) { console.error("coverage below gate"); process.exit(1); }
          '

      # A scan that did not run is not a clean scan: the step fails on a missing tool rather
      # than reporting zero findings.
      - name: Security gate (block: \${{ env.${envName("security_severity_block")} }})
        run: |
          python3 -m pip install --quiet semgrep
          semgrep --config auto --json --quiet --metrics off pipeline > semgrep.json
          node -e '
            const d = require("./semgrep.json");
            const block = String(process.env.${envName("security_severity_block")}).split(",");
            const sev = (r) => String(r.extra?.severity ?? "info").toLowerCase();
            const map = { error: "high", warning: "medium", info: "low" };
            const hits = (d.results || []).filter((r) => block.includes(map[sev(r)] ?? sev(r)));
            console.log("blocking findings:", hits.length);
            if (hits.length) process.exit(1);
          '

      - name: Pipeline run (gates + chaos + self-audit)
        env:
          RUN_ID: \${{ steps.meta.outputs.run_id }}
          GIT_SHA: \${{ steps.meta.outputs.git_sha }}
        run: npx tsx pipeline/bin/run.ts --profile simple --pool 3

      - name: Upload artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-\${{ steps.meta.outputs.run_id }}
          path: |
            coverage-pipeline/
            semgrep.json
          if-no-files-found: warn
`;
}

/**
 * Extract every `GATE_*` value the rendered YAML declares.
 *
 * Used by the drift test: whatever the emitter produced must equal the source object, so a
 * future edit to the template that hard-codes a number is caught immediately.
 */
export function parseThresholdEnv(yaml: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of String(yaml ?? "").split("\n")) {
    const m = line.match(/^\s{2}(GATE_[A-Z0-9_]+):\s*"(.*)"\s*$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}
