// Self-updating prompt block (pure).
//
// WHY THIS EXISTS
// The brief is explicit: "her işlemde güncelle" — update the prompt on every operation, with
// the most current, most efficient working knowledge. A master prompt that quotes a baseline
// table nobody re-measures becomes fiction the moment the system changes; the source document
// already carried "illustrative" numbers presented as if measured.
//
// So this module renders a MEASURED block and splices it between two markers, replacing any
// previous one. It is pure — it takes the report and returns text — so the exact bytes written
// into a file the operator owns are unit-tested rather than hoped for.
//
// It never touches anything outside its markers. The prompt is Emre's document; this writes
// one clearly-delimited section into it and leaves every other line untouched.
import type { RunReport } from "./report";
import type { Summary } from "./stats";

export const BEGIN = "<!-- MEASURED:BEGIN — auto-generated by pipeline/lib/prompt-sync.ts. Do not edit inside. -->";
export const END = "<!-- MEASURED:END -->";

export interface SyncInput {
  report: RunReport;
  /** Per-step p95 across the run set, worst-first. */
  stepSummaries: Record<string, Summary>;
  /** Gaps the self-audit still reports open. */
  missing: string[];
  /** Findings the operator should read as "the source prompt was wrong about this". */
  corrections: string[];
}

/** Worst-p95-first, because the budget is spent where the tail is. */
function topSteps(steps: Record<string, Summary>, n = 6): Array<[string, Summary]> {
  return Object.entries(steps).sort((a, b) => b[1].p95 - a[1].p95).slice(0, n);
}

export function renderBlock(i: SyncInput): string {
  const r = i.report;
  const t = r.total;
  const gate = (name: string) => r.decision.gates.find((g) => g.name === name);
  const g = (name: string) => {
    const x = gate(name);
    if (!x) return "—";
    return `${x.ok ? "PASS" : x.measured === null ? "MISS" : "FAIL"} ${x.measured ?? "—"} / ${x.limit}`;
  };

  const lines = [
    BEGIN,
    "",
    "## 📊 MEASURED — last real run (auto-updated, do not hand-edit)",
    "",
    `run_id \`${r.env.run_id}\` · ${r.env.timestamp} · profile \`${r.profile}\` · workflow v${r.workflow_version}`,
    `env ${r.env.os}/${r.env.arch} · cpu ${r.env.cpu_count} · mem ${r.env.mem_gb} GB · node ${r.env.node} · git \`${r.env.git_sha.slice(0, 8)}\``,
    "",
    "### End-to-end latency",
    "",
    "| metric | value |",
    "|---|---:|",
    `| p50 | ${t.p50} ms |`,
    `| p95 | ${t.p95} ms |`,
    `| p99 | ${t.p99} ms${t.p99Reliable === false ? ` ⚠️ n<100, kuyruk güvenilmez (=max)` : ""} |`,
    `| p999 | ${t.p999} ms${t.p999Reliable === false ? ` ⚠️ n<1000, kuyruk güvenilmez (=max)` : ""} |`,
    `| stddev | ${t.stddev} ms |`,
    `| cv | ${t.cv} |`,
    `| 95% CI | [${t.ci95_lo.toFixed(0)}, ${t.ci95_hi.toFixed(0)}] ms |`,
    `| runs (n) | ${t.n} |`,
    "",
    "### Where the budget goes (step p95)",
    "",
    "| step | p95 ms | n |",
    "|---|---:|---:|",
    ...topSteps(i.stepSummaries).map(([id, s]) => `| ${id} | ${s.p95} | ${s.n} |`),
    "",
    "### Quality gates",
    "",
    "| gate | measured / limit |",
    "|---|---|",
    `| p95(think) | ${g("p95(think)")} |`,
    `| p95(sandbox_test) | ${g("p95(sandbox_test)")} |`,
    `| p95(total) | ${g("p95(total)")} |`,
    `| error_rate | ${g("error_rate")} |`,
    `| coverage | ${g("coverage")} |`,
    `| security | ${g("security")} |`,
    `| chaos | ${g("chaos")} |`,
    "",
    `**decision:** \`go_ahead=${r.decision.go_ahead}\`${r.decision.weak_evidence ? " _(weak evidence)_" : ""} — ${r.decision.reason}`,
    `**status:** \`${r.status}\`` + (i.missing.length ? ` — self-audit gaps: ${i.missing.join(", ")}` : " — no blind spots"),
    `**efficiency:** cache hit ${r.cache.ratio} · parallelism ${r.parallelism}× · error rate ${r.error_rate_pct}%`,
    "",
  ];

  if (i.corrections.length) {
    lines.push(
      "### Corrections to this prompt (measured, not assumed)",
      "",
      // These exist because the source document asserted things this machine disproved. A
      // prompt that keeps its disproven claims teaches them to every model that reads it.
      ...i.corrections.map((c) => `- ${c}`),
      "",
    );
  }

  lines.push(END);
  return lines.join("\n");
}

/**
 * Splice the block into a document.
 *
 * Replaces an existing block between the markers; otherwise appends. Everything outside the
 * markers is preserved byte-for-byte — the operator's prose, ordering and formatting are not
 * this module's to rewrite.
 */
export function spliceBlock(doc: string, block: string): string {
  const src = String(doc ?? "");
  const b = src.indexOf(BEGIN);
  const e = src.indexOf(END);
  if (b >= 0 && e > b) {
    return src.slice(0, b) + block + src.slice(e + END.length);
  }
  const sep = src.endsWith("\n") ? "\n" : "\n\n";
  return src + sep + block + "\n";
}

/** True when the document already carries a measured block. */
export function hasBlock(doc: string): boolean {
  const src = String(doc ?? "");
  const b = src.indexOf(BEGIN);
  return b >= 0 && src.indexOf(END) > b;
}
