// Zero-dep GitHub REST client (node global fetch — no Octokit). Posts Audit-as-a-Service findings
// to a client repo as a GitHub Issue so the paid deliverable lands as a native GitHub artifact.
// PAT auth (fine-grained: issues:write) read from the AES-256-GCM vault. Choke-point-safe:
// server-side only; the CLI never imports this. The Checks API needs a GitHub App (Phase 1b).

const GH_API = "https://api.github.com";

const ghHeaders = (token: string): Record<string, string> => ({
  Authorization: `Bearer ${token}`,
  Accept: "application/vnd.github+json",
  "X-GitHub-Api-Version": "2022-11-28",
  "User-Agent": "ollamas-audit-service", // GitHub rejects requests without a User-Agent
  "Content-Type": "application/json",
});

export interface Finding {
  file?: string;
  name?: string;
  line?: number | string;
  symptom?: string;
  fix?: string;
  severity?: string;
}

// Severity ordering for a triage-friendly issue body (unknown severities sort last).
const SEV_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"];
function sevRank(s?: string): number {
  const i = SEV_ORDER.indexOf(String(s || "").toUpperCase());
  return i === -1 ? SEV_ORDER.length : i;
}

/** Pure: render findings.json into a severity-sorted GitHub-flavored markdown issue body. */
export function buildIssueBody(findings: Finding[], opts?: { model?: string }): string {
  const list = Array.isArray(findings) ? [...findings] : [];
  list.sort((a, b) => sevRank(a.severity) - sevRank(b.severity));
  const out: string[] = [
    "## ollamas automated code audit",
    "",
    `**${list.length} finding(s)**${opts?.model ? ` · auditor: \`${opts.model}\`` : ""}. ` +
      "Candidate findings — verify before acting (Tier-1 reproduction available on request).",
  ];
  if (!list.length) {
    out.push("", "_No findings._");
    return out.join("\n");
  }
  let lastSev = "";
  for (const f of list) {
    const sev = String(f.severity || "UNSPECIFIED").toUpperCase();
    if (sev !== lastSev) {
      out.push("", `### ${sev}`, "");
      lastSev = sev;
    }
    const loc = [f.file, f.line].filter((x) => x != null && x !== "").join(":");
    const head = loc || f.name || "?";
    out.push(`- **${head}**${f.name && loc ? ` (\`${f.name}\`)` : ""}`);
    if (f.symptom) out.push(`  - symptom: ${f.symptom}`);
    if (f.fix) out.push(`  - fix: ${f.fix}`);
  }
  out.push("", "---", "_Generated by ollamas Audit-as-a-Service — $0 local-model engine._");
  return out.join("\n");
}

export interface RepoSlug {
  owner: string;
  repo: string;
}

/** Pure: parse "owner/name" tolerating a full github URL or a trailing .git / slashes. */
export function parseRepoSlug(input: string): RepoSlug | null {
  if (!input || typeof input !== "string") return null;
  const s = input
    .trim()
    .replace(/^https?:\/\/github\.com\//i, "")
    .replace(/\/+$/, "") // strip trailing slashes FIRST so the .git suffix is reachable
    .replace(/\.git$/i, "");
  const parts = s.split("/").filter(Boolean);
  if (parts.length < 2) return null;
  return { owner: parts[0], repo: parts[1] };
}

export interface GhResult<T> {
  ok: boolean;
  status: number;
  data?: T;
  error?: string;
}

async function ghRequest<T>(
  method: string,
  apiPath: string,
  token: string,
  body?: unknown,
  signal?: AbortSignal,
): Promise<GhResult<T>> {
  if (!token) return { ok: false, status: 0, error: "no GitHub token configured" };
  try {
    const res = await fetch(`${GH_API}${apiPath}`, {
      method,
      headers: ghHeaders(token),
      body: body == null ? undefined : JSON.stringify(body),
      signal,
    });
    const text = await res.text();
    let data: unknown;
    try {
      data = text ? JSON.parse(text) : undefined;
    } catch {
      /* non-JSON response */
    }
    if (!res.ok) {
      const msg =
        (data && typeof data === "object" && (data as { message?: string }).message) ||
        text.slice(0, 200) ||
        res.statusText;
      return { ok: false, status: res.status, error: `GitHub ${res.status}: ${msg}` };
    }
    return { ok: true, status: res.status, data: data as T };
  } catch (e) {
    return { ok: false, status: 0, error: `fetch failed: ${(e as Error).message}` };
  }
}

export function getRepo(owner: string, repo: string, token: string, signal?: AbortSignal) {
  return ghRequest<{ full_name: string; permissions?: Record<string, boolean> }>(
    "GET",
    `/repos/${owner}/${repo}`,
    token,
    undefined,
    signal,
  );
}

export function createIssue(args: {
  owner: string;
  repo: string;
  title: string;
  body: string;
  token: string;
  signal?: AbortSignal;
}) {
  return ghRequest<{ number: number; html_url: string }>(
    "POST",
    `/repos/${args.owner}/${args.repo}/issues`,
    args.token,
    { title: args.title, body: args.body },
    args.signal,
  );
}
