name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pnpm install

      - name: Terraform apply
        run: |
          pnpm run terraform:apply

      - name: Helm upgrade
        run: |
          pnpm run helm:upgrade